sudo: required

language: node_js
node_js:
  - 14

branches:
  only:
    - master

services: 
  - docker

before_install:
  - echo "docker build start"
  - cat .env.example | envsub > .env
  - docker build -f Dockerfile.travis.test -t test:v1 .

script:
  - docker run -e CI=true test:v1 npm run test -- --coverage

after_success:
  - echo "test success"