FROM node:14.5.0
WORKDIR /usr/server
COPY package.json .
COPY package-lock.json .
COPY tsconfig.json .
COPY tsconfig-build.json .
COPY .env .
COPY src ./src
RUN npm i \
&& npm i typescript -g \
RUN npm run build
EXPOSE 3000
CMD npm start