FROM node:alpine
WORKDIR /usr/server
COPY package.json .
COPY package-lock.json .
RUN npm i \
&& npm i typescript -g \
&& npm i pm2 -g
COPY tsconfig.json .
COPY tsconfig-build.json .
COPY jest.config.js .
COPY .env .
COPY src ./src
COPY tests ./tests
RUN npm run build
EXPOSE 3000